foryer-model-wo-throttle-1:
	KERAS_BACKEND=tensorflow python ./foryer_model_wo_throttle.py with ./configs/foryer_model_wo_throttle_1.json

# Jogging
jogging-model-wo-balance-1:
	KERAS_BACKEND=tensorflow python ./jogging_model_wo_balance.py with ./configs/jogging_model_wo_balance_1.json
