foryer-model-wo-balance-1:
	KERAS_BACKEND=tensorflow python ./foryer_model_wo_balance.py.py with ./configs/foryer_model_wo_balance_1.json

# Jogging
jogging-model-wo-balance-1:
	KERAS_BACKEND=tensorflow python ./jogging_model_wo_balance.py with ./configs/jogging_model_wo_balance_1.json

jogging-model-wo-balance-2:
	KERAS_BACKEND=tensorflow python ./jogging_model_wo_balance.py with ./configs/jogging_model_wo_balance_2.json

jogging-model-wo-balance-3:
	KERAS_BACKEND=tensorflow python ./jogging_model_wo_balance.py with ./configs/jogging_model_wo_balance_3.json

jogging-model-wo-balance-4:
	KERAS_BACKEND=tensorflow python ./jogging_model_wo_balance.py with ./configs/jogging_model_wo_balance_4.json

jogging-model-wo-balance-5:
	KERAS_BACKEND=tensorflow python ./jogging_model_wo_balance.py with ./configs/jogging_model_wo_balance_5.json

jogging-model-wo-balance-6:
	KERAS_BACKEND=tensorflow python ./jogging_model_wo_balance.py with ./configs/jogging_model_wo_balance_6.json

jogging-model-wo-balance-7:
	KERAS_BACKEND=tensorflow python ./jogging_model_wo_balance.py with ./configs/jogging_model_wo_balance_7.json

jogging-model-wo-balance-8:
	KERAS_BACKEND=tensorflow python ./jogging_model_wo_balance.py with ./configs/jogging_model_wo_balance_8.json

jogging-model-wo-balance-9:
	KERAS_BACKEND=tensorflow python ./jogging_model_wo_balance.py with ./configs/jogging_model_wo_balance_9.json

jogging-model-wo-balance-10:
	KERAS_BACKEND=tensorflow python ./jogging_model_wo_balance.py with ./configs/jogging_model_wo_balance_10.json
